version: '3.8'

services:
  backend:
    image: bacuaban77/dm-conf-backend:latest
    container_name: dm-config-backend
    ports:
      - "8080:8080"
    volumes:
      - /opt/dm:/opt/dm  # Configuration files + reboot trigger file
      - /etc/network/interfaces:/etc/network/interfaces
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - dm-network
    restart: unless-stopped

  frontend:
    image: bacuaban77/dm-conf-frontend:latest
    container_name: dm-config-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - dm-network
    restart: unless-stopped

networks:
  dm-network:
    driver: bridge

